### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ThibaultLemaire** [alter/minitroopers.com#8]
Well maybe now the readme needs a little bit of refreshing. There's a bunch of other minitroopers bots out there, maybe we could show what makes this one unique, and also provide some info on how to use it for novices ?

Want me to do it?

**Comment by alter** [comment]
Yeah, why not, also, I did it just4fun, so if you'd like to work on it hardly, you can add contribution file with link on your repo, and make it the main one :)

**Comment by ThibaultLemaire** [comment]
So you want me to take over?

It wasn't really my intention, and I don't plan on making many more changes (at least for now).

I don't know much about this feature, but maybe you could add me to the "collaborators" (somewhere around in the settings) for the time being? So you don't have to accept my PRs.

**Comment by alter** [comment]
I've added your to collaborators of this repository, you're welcome =)

**Comment by ThibaultLemaire** [comment]
Alright, thanks! But I'll leave that open until I properly update the README
